### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by JoeTheBob** [Leo3418/HBWHelper#3]
so every time I try to install forge 1.8.9 for HBW helper I get the same crash message can anyone help? i am pretty clueless and I've tried uninstalling and re- installing forge 1.8.9
crash message:
 ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 3/24/21 4:08 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.fml.common.Loader$ModIdComparator.compare(Loader.java:368)
	at net.minecraftforge.fml.common.Loader$ModIdComparator.compare(Loader.java:363)
	at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:376)
	at java.util.TreeMap.getEntry(TreeMap.java:345)
	at java.util.TreeMap.get(TreeMap.java:278)
	at com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:192)
	at com.google.common.collect.AbstractSetMultimap.put(AbstractSetMultimap.java:121)
	at com.google.common.collect.TreeMultimap.put(TreeMultimap.java:78)
	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:379)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:357)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:481)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:205)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraftforge.fml.common.Loader$ModIdComparator.compare(Loader.java:368)
	at net.minecraftforge.fml.common.Loader$ModIdComparator.compare(Loader.java:363)
	at java.util.TreeMap.getEntryUsingComparator(TreeMap.java:376)
	at java.util.TreeMap.getEntry(TreeMap.java:345)
	at java.util.TreeMap.get(TreeMap.java:278)
	at com.google.common.collect.AbstractMapBasedMultimap.put(AbstractMapBasedMultimap.java:192)
	at com.google.common.collect.AbstractSetMultimap.put(AbstractSetMultimap.java:121)
	at com.google.common.collect.TreeMultimap.put(TreeMultimap.java:78)
	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:379)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:357)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:481)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:205)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 823421496 bytes (785 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.0.1656 6 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1656.jar) 
		Forge{11.15.0.1656} [Minecraft Forge] (forge-1.8.9-11.15.0.1656.jar) 
		null{1.0} [null] (baritone-standalone-forge-1.6.3.jar) 
		hbwhelper{1.0.3} [HBW Helper] (hbwhelper-1.8.9-1.0.3.jar) 
		null{1.0} [null] (MinecraftCapes+Forge+1.16.4-v10.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GT 720/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.0.1656
	LWJGL: 2.9.4
	OpenGL: GeForce GT 720/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: !   §6§lDeos 2k Pack§r§6 (v1.3).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

**Comment by Leo3418** [comment]
Hey there! Please try the following things and see if the issue persists:

- You are not using a *recommended* build of Minecraft Forge. Please try Forge 11.15.1.1722, which is the newest recommended version for Minecraft 1.8.9. You may download it from here: <https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.8.9.html>
- You are not using the latest release of this mod. Please try the latest release over here: <https://github.com/Leo3418/HBWHelper/releases/latest>
- You are using this mod with other mods, and the debugging information you have provided does not suggest that this mod is the issue's root cause. Try removing all other mods and then starting Minecraft Forge with this mod only.
- You are using an old version of Java. As of now, the latest Java 8 release is 1.8.0_282. Please update Java if all previous steps have failed.

If the issue persists after you have tried **all** these steps, please post any new error messages and debug logs for further assistance.

**Comment by Leo3418** [comment]
Because of inactivity for a week, the issue is being closed. If you would like to provide more information at any time, please do not hesitate to post it here, and I will reopen this issue if necessary.
